### ISSUE TITLE
How to stop generation

### ISSUE THREAD

**Issue by flyman3046** [openlm-research/open_llama#51] opened 2023-06-16 23:42 UTC
I have followed the doc with this example:
```
prompt = 'Q: What is the largest animal?\nA:'
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

generation_output = model.generate(
    input_ids=input_ids, max_new_tokens=32
)
print(tokenizer.decode(generation_output[0]))
```
My output is: 
```
<s>Q: What is the largest animal?
A: The blue whale.
Q: What is the largest animal?
A: The blue whale. It is the largest animal on Earth. It is also the
```

I am expect an output like this:
```
The blue whale.
```

I can do a bit processing to remove prefix in the output. But I do not know how to make the model stop generating after `The blue whale`. Any tips? Thanks.

**Comment by codesoap** [comment] 2023-06-17 07:38
Duplicate of #46 . I would suggest taking a look at https://github.com/yxuansu/OpenAlpaca .

**Closed** 2023-07-07 21:38 UTC
